import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro', // docs/intro.md ("Why Physical AI Matters")
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI',
      link: {
        type: 'doc',
        id: 'chapter1/chapter1-overview',
      },
      items: [
        {
            type: 'autogenerated',
            dirName: 'chapter1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: ROS 2 Fundamentals',
      link: {
        type: 'doc',
        id: 'chapter2/chapter2-overview',
      },
      items: [
        {
          type: 'category',
          label: 'Module 1: The Robotic Nervous System (ROS 2)',
          link: {
            type: 'doc',
            id: 'chapter2/module1-detailing',
          },
          items: [
            'chapter2/module1/lesson1',
            'chapter2/module1/lesson2',
            'chapter2/module1/lesson3',
            'chapter2/module1/lesson4',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Robot Simulation',
      link: {
        type: 'doc',
        id: 'chapter3/chapter3-overview',
      },
      items: [
        {
          type: 'category',
          label: 'Module 2: The Digital Twin (Gazebo & Unity)',
          link: {
            type: 'doc',
            id: 'chapter3/module2-detailing',
          },
          items: [
            'chapter3/module2/lesson1',
            'chapter3/module2/lesson2',
            'chapter3/module2/lesson3',
            'chapter3/module2/lesson4',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: NVIDIA Isaac Integration',
      link: {
        type: 'doc',
        id: 'chapter4/chapter4-overview',
      },
      items: [
        {
          type: 'category',
          label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
          link: {
            type: 'doc',
            id: 'chapter4/module3-detailing',
          },
          items: [
            'chapter4/module3/lesson1',
            'chapter4/module3/lesson2',
            'chapter4/module3/lesson3',
            'chapter4/module3/lesson4',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 5: Humanoid Development',
      link: {
        type: 'doc',
        id: 'chapter5/chapter5-overview',
      },
      items: [
        {
          type: 'category',
          label: 'Module 4: Vision-Language-Action (VLA)',
          link: {
            type: 'doc',
            id: 'chapter5/module4-detailing',
          },
          items: [
            'chapter5/module4/lesson1',
            'chapter5/module4/lesson2',
            'chapter5/module4/lesson3',
            'chapter5/module4/lesson4',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 6: Conversational Robotics (VLA)',
      link: {
        type: 'doc',
        id: 'chapter6/chapter6-overview',
      },
      items: [{ type: 'autogenerated', dirName: 'chapter6' }],
    },
    {
      type: 'category',
      label: 'Chapter 7: Capstone Project & Assessments',
      link: {
        type: 'doc',
        id: 'chapter7/chapter7-overview',
      },
      items: [{ type: 'autogenerated', dirName: 'chapter7' }],
    },
    'hardware-requirements', // docs/hardware-requirements.md
    'assessments', // docs/assessments.md
  ],
};

export default sidebars;
