import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro', // docs/intro.md
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI',
      link: {
        type: 'doc',
        id: 'chapter1/chapter1-overview',
      },
      items: [
        {
            type: 'autogenerated',
            dirName: 'chapter1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: ROS 2 Fundamentals',
      link: {
        type: 'doc',
        id: 'chapter2/chapter2-overview',
      },
      items: [{ type: 'autogenerated', dirName: 'chapter2' }],
    },
    {
      type: 'category',
      label: 'Chapter 3: Robot Simulation',
      link: {
        type: 'doc',
        id: 'chapter3/chapter3-overview',
      },
      items: [{ type: 'autogenerated', dirName: 'chapter3' }],
    },
    {
      type: 'category',
      label: 'Chapter 4: NVIDIA Isaac Integration',
      link: {
        type: 'doc',
        id: 'chapter4/chapter4-overview',
      },
      items: [{ type: 'autogenerated', dirName: 'chapter4' }],
    },
    {
      type: 'category',
      label: 'Chapter 5: Humanoid Development',
      link: {
        type: 'doc',
        id: 'chapter5/chapter5-overview',
      },
      items: [{ type: 'autogenerated', dirName: 'chapter5' }],
    },
    {
      type: 'category',
      label: 'Chapter 6: Conversational Robotics (VLA)',
      link: {
        type: 'doc',
        id: 'chapter6/chapter6-overview',
      },
      items: [{ type: 'autogenerated', dirName: 'chapter6' }],
    },
    {
      type: 'category',
      label: 'Chapter 7: Capstone Project & Assessments',
      link: {
        type: 'doc',
        id: 'chapter7/chapter7-overview',
      },
      items: [{ type: 'autogenerated', dirName: 'chapter7' }],
    },
    'hardware', // docs/hardware.md
    // 'assessments', // Will be created in T011, uncomment later
  ],
};

export default sidebars;
